### ISSUE TITLE
Can't resolve address using NIO on Android 2.2

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#125]
```
12-18 13:56:25.383: W/System.err(290): java.lang.NullPointerException
12-18 13:56:25.383: W/System.err(290):     at org.apache.harmony.nio.internal.SelectorImpl.wakeup(SelectorImpl.java:418)
12-18 13:56:25.383: W/System.err(290):     at org.apache.harmony.nio.internal.SelectorImpl.implCloseSelector(SelectorImpl.java:157)
12-18 13:56:25.383: W/System.err(290):     at java.nio.channels.spi.AbstractSelector.close(AbstractSelector.java:64)
12-18 13:56:25.383: W/System.err(290):     at org.xbill.DNS.Client.cleanup(Client.java:54)
12-18 13:56:25.383: W/System.err(290):     at org.xbill.DNS.UDPClient.sendrecv(UDPClient.java:153)
12-18 13:56:25.383: W/System.err(290):     at org.xbill.DNS.SimpleResolver.send(SimpleResolver.java:257)
12-18 13:56:25.383: W/System.err(290):     at org.xbill.DNS.ExtendedResolver$Resolution.start(ExtendedResolver.java:95)
12-18 13:56:25.383: W/System.err(290):     at org.xbill.DNS.ExtendedResolver.send(ExtendedResolver.java:358)
12-18 13:56:25.383: W/System.err(290):     at org.xbill.DNS.Lookup.lookup(Lookup.java:467)
12-18 13:56:25.383: W/System.err(290):     at org.xbill.DNS.Lookup.resolve(Lookup.java:519)
12-18 13:56:25.383: W/System.err(290):     at org.xbill.DNS.Lookup.run(Lookup.java:533)
12-18 13:56:25.383: W/System.err(290):     at org.xbill.DNS.Address.lookupHostName(Address.java:237)
12-18 13:56:25.383: W/System.err(290):     at org.xbill.DNS.Address.getAllByName(Address.java:281)
12-18 13:56:25.402: W/System.err(290):     at com.xabber.android.data.connection.DNSManager.fetchAddresses(DNSManager.java:179)
```

**Comment by andrewnenakhov** [comment]
Is there still anyone on Android 2.2? )
