### ISSUE TITLE
Freeze on network change

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#127]
```
  at java.nio.channels.spi.AbstractInterruptibleChannel$1.run(AbstractInterruptibleChannel.java:46)
  at java.lang.Thread.interrupt(Thread.java:674)
  at java.util.concurrent.ThreadPoolExecutor.interruptWorkers(ThreadPoolExecutor.java:699)
  at java.util.concurrent.ThreadPoolExecutor.shutdownNow(ThreadPoolExecutor.java:1355)
  at java.util.concurrent.Executors$DelegatedExecutorService.shutdownNow(Executors.java:602)
  at com.xabber.android.data.connection.ConnectionThread.shutdown(ConnectionThread.java:601)
  at com.xabber.android.data.connection.ConnectionItem.onDisconnect(ConnectionItem.java:256)
  at com.xabber.android.data.connection.ConnectionItem.onClose(ConnectionItem.java:264)
  at com.xabber.android.data.connection.AccountItem.onClose(AccountItem.java:462)
  at com.xabber.android.data.connection.ConnectionItem.updateConnection(ConnectionItem.java:122)
  at com.xabber.android.data.connection.ConnectionManager.updateConnections(ConnectionManager.java:133)
  at com.xabber.android.data.connection.NetworkManager.onUnavailable(NetworkManager.java:200)
  at com.xabber.android.data.connection.NetworkManager.onNetworkChange(NetworkManager.java:153)
  at com.xabber.android.data.connection.NetworkManager$ConnectivityReceiver.onReceive(NetworkManager.java:230)
```

**Comment by andrewnenakhov** [comment]
Resolved a while ago, but simliar things do happen on other reasons.
