### ISSUE TITLE
Crash when group removed from system contact list

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#140]
```
Caused by: android.database.sqlite.SQLiteException: ambiguous column name: _id (code 1): , while compiling:
SELECT groups._id FROM groups JOIN accounts ON accounts._id = groups.account_id WHERE _id IN (34,35,32,33,38,39,36,37,26,29,28,31,30)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
at android.content.ContentProviderProxy.delete(ContentProviderNative.java:546)
at android.content.ContentResolver.delete(ContentResolver.java:966)
at com.xabber.android.data.roster.SyncManager.removeByIds(SyncManager.java:479)
```

**Comment by grigoryfedorov** [comment]
Seems to be not actual, since we do not support system contacts
