### ISSUE TITLE
Name loaded from system contact list can be null

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#252]
`````` java.lang.NullPointerException
at com.xabber.android.data.roster.RosterManager.onPacket(RosterManager.java:577)
at com.xabber.android.data.connection.ConnectionManager.processPacket(ConnectionManager.java:275)
at com.xabber.android.data.connection.ConnectionThread$18.run(ConnectionThread.java:578)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:153)
at android.app.ActivityThread.main(ActivityThread.java:4987)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
at dalvik.system.NativeStart.main(Native Method)```
``````

**Comment by andrewnenakhov** [comment]
should fix this in 0.11.0 i guess

**Comment by andrewnenakhov** [comment]
removed contact list integration for now, postponing
