### ISSUE TITLE
Xabber authorization errors with jabber.org lately

### ISSUE THREAD

**Issue by aelmahmoudy** [redsolution/xabber-android#277]
Lately Xabber sometimes give me authorization errors when I connect to jabber.org specifically. Today it doesn't connect at all !

I got this on the logcat:

```
01-29 09:33:45.486 20908 21753 W System.err: java.lang.InterruptedException
01-29 09:33:45.491 20908 21753 W System.err:    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1195)
01-29 09:33:45.491 20908 21753 W System.err:    at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:309)
01-29 09:33:45.491 20908 21753 W System.err:    at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:309)
01-29 09:33:45.491 20908 21753 W System.err:    at org.jivesoftware.smack.PacketWriter.sendPacket(PacketWriter.java:156)
01-29 09:33:45.491 20908 21753 W System.err:    at org.jivesoftware.smack.XMPPConnection.shutdown(XMPPConnection.java:421)
01-29 09:33:45.491 20908 21753 W System.err:    at org.jivesoftware.smack.XMPPConnection.disconnect(XMPPConnection.java:480)
01-29 09:33:45.491 20908 21753 W System.err:    at org.jivesoftware.smack.Connection.disconnect(Connection.java:476)
01-29 09:33:45.491 20908 21753 W System.err:    at com.xabber.android.data.connection.ConnectionThread.authorization(ConnectionThread.java:537)
01-29 09:33:45.491 20908 21753 W System.err:    at com.xabber.android.data.connection.ConnectionThread.access$800(ConnectionThread.java:54)
01-29 09:33:45.491 20908 21753 W System.err:    at com.xabber.android.data.connection.ConnectionThread$14.run(ConnectionThread.java:494)
01-29 09:33:45.491 20908 21753 W System.err:    at com.xabber.android.data.connection.ConnectionThread$20.run(ConnectionThread.java:663)
01-29 09:33:45.491 20908 21753 W System.err:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
01-29 09:33:45.491 20908 21753 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
01-29 09:33:45.491 20908 21753 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
01-29 09:33:45.491 20908 21753 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
01-29 09:33:45.491 20908 21753 W System.err:    at java.lang.Thread.run(Thread.java:856)
```

**Comment by andrewnenakhov** [comment]
Jabber.org does not seem to be alive now, at least they didn't allow registration since.. 2013!
