### ISSUE TITLE
Xabber crashes on text selection

### ISSUE THREAD

**Issue by aelmahmoudy** [redsolution/xabber-android#384]
Since the upgrade to 0.10.46, Xabber crashes whenever some text is select, this text can be chat input text, or text input in some dialog.
Here's the logcat at crash:
```
I/com.xabber.android.ui.ChatViewerFragment$5@41fd0748(12475): afterTextChanged
I/com.xabber.android.ui.ChatViewerFragment$5@41fd0748(12475): afterTextChanged
I/com.xabber.android.ui.ChatViewerFragment$5@41fd0748(12475): afterTextChanged
I/com.xabber.android.ui.ChatViewerFragment$5@41fd0748(12475): afterTextChanged
E/InputEventReceiver(12475): Exception dispatching input event.
E/MessageQueue-JNI(12475): Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI(12475): android.view.InflateException: Binary XML file line #19: Error inflating class android.support.v7.internal.widget.ActionBarContextView
E/MessageQueue-JNI(12475): 	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
E/MessageQueue-JNI(12475): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
E/MessageQueue-JNI(12475): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
E/MessageQueue-JNI(12475): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/MessageQueue-JNI(12475): 	at android.support.v7.internal.widget.ViewStubCompat.inflate(ViewStubCompat.java:201)
E/MessageQueue-JNI(12475): 	at android.support.v7.app.ActionBarActivityDelegateBase.startSupportActionModeFromWindow(ActionBarActivityDelegateBase.java:628)
E/MessageQueue-JNI(12475): 	at android.support.v7.app.ActionBarActivityDelegate$1.startActionMode(ActionBarActivityDelegate.java:100)
E/MessageQueue-JNI(12475): 	at android.support.v7.widget.WindowCallbackWrapper.startActionMode(WindowCallbackWrapper.java:69)
E/MessageQueue-JNI(12475): 	at android.support.v7.internal.app.ToolbarActionBar.startActionMode(ToolbarActionBar.java:204)
E/MessageQueue-JNI(12475): 	at android.support.v7.app.ActionBarActivityDelegateBase.startSupportActionMode(ActionBarActivityDelegateBase.java:570)
E/MessageQueue-JNI(12475): 	at android.support.v7.app.ActionBarActivityDelegateHC.startActionModeForChild(ActionBarActivityDelegateHC.java:56)
E/MessageQueue-JNI(12475): 	at android.support.v7.internal.widget.NativeActionModeAwareLayout.startActionModeForChild(NativeActionModeAwareLayout.java:44)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
E/MessageQueue-JNI(12475): 	at android.view.View.startActionMode(View.java:4543)
E/MessageQueue-JNI(12475): 	at android.widget.Editor.startSelectionActionMode(Editor.java:1551)
E/MessageQueue-JNI(12475): 	at android.widget.Editor$SelectionModifierCursorController.onTouchEvent(Editor.java:3656)
E/MessageQueue-JNI(12475): 	at android.widget.Editor.onTouchEvent(Editor.java:1036)
E/MessageQueue-JNI(12475): 	at android.widget.TextView.onTouchEvent(TextView.java:7691)
E/MessageQueue-JNI(12475): 	at android.view.View.dispatchTouchEvent(View.java:7713)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/MessageQueue-JNI(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/MessageQueue-JNI(12475): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2326)
E/MessageQueue-JNI(12475): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1568)
E/MessageQueue-JNI(12475): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2495)
E/MessageQueue-JNI(12475): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2274)
E/MessageQueue-JNI(12475): 	at android.view.View.dispatchPointerEvent(View.java:7893)
E/MessageQueue-JNI(12475): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3947)
E/MessageQueue-JNI(12475): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3826)
E/MessageQueue-JNI(12475): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
E/MessageQueue-JNI(12475): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
E/MessageQueue-JNI(12475): 	at android.view.ViewRootI
D/AndroidRuntime(12475): Shutting down VM
W/dalvikvm(12475): threadid=1: thread exiting with uncaught exception (group=0x41887ba8)
E/AndroidRuntime(12475): FATAL EXCEPTION: main
E/AndroidRuntime(12475): Process: com.xabber.androiddev, PID: 12475
E/AndroidRuntime(12475): android.view.InflateException: Binary XML file line #19: Error inflating class android.support.v7.internal.widget.ActionBarContextView
E/AndroidRuntime(12475): 	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
E/AndroidRuntime(12475): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
E/AndroidRuntime(12475): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
E/AndroidRuntime(12475): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime(12475): 	at android.support.v7.internal.widget.ViewStubCompat.inflate(ViewStubCompat.java:201)
E/AndroidRuntime(12475): 	at android.support.v7.app.ActionBarActivityDelegateBase.startSupportActionModeFromWindow(ActionBarActivityDelegateBase.java:628)
E/AndroidRuntime(12475): 	at android.support.v7.app.ActionBarActivityDelegate$1.startActionMode(ActionBarActivityDelegate.java:100)
E/AndroidRuntime(12475): 	at android.support.v7.widget.WindowCallbackWrapper.startActionMode(WindowCallbackWrapper.java:69)
E/AndroidRuntime(12475): 	at android.support.v7.internal.app.ToolbarActionBar.startActionMode(ToolbarActionBar.java:204)
E/AndroidRuntime(12475): 	at android.support.v7.app.ActionBarActivityDelegateBase.startSupportActionMode(ActionBarActivityDelegateBase.java:570)
E/AndroidRuntime(12475): 	at android.support.v7.app.ActionBarActivityDelegateHC.startActionModeForChild(ActionBarActivityDelegateHC.java:56)
E/AndroidRuntime(12475): 	at android.support.v7.internal.widget.NativeActionModeAwareLayout.startActionModeForChild(NativeActionModeAwareLayout.java:44)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
E/AndroidRuntime(12475): 	at android.view.View.startActionMode(View.java:4543)
E/AndroidRuntime(12475): 	at android.widget.Editor.startSelectionActionMode(Editor.java:1551)
E/AndroidRuntime(12475): 	at android.widget.Editor$SelectionModifierCursorController.onTouchEvent(Editor.java:3656)
E/AndroidRuntime(12475): 	at android.widget.Editor.onTouchEvent(Editor.java:1036)
E/AndroidRuntime(12475): 	at android.widget.TextView.onTouchEvent(TextView.java:7691)
E/AndroidRuntime(12475): 	at android.view.View.dispatchTouchEvent(View.java:7713)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
E/AndroidRuntime(12475): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(12475): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2326)
E/AndroidRuntime(12475): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1568)
E/AndroidRuntime(12475): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2495)
E/AndroidRuntime(12475): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2274)
E/AndroidRuntime(12475): 	at android.view.View.dispatchPointerEvent(View.java:7893)
E/AndroidRuntime(12475): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3947)
E/AndroidRuntime(12475): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3826)
E/AndroidRuntime(12475): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
E/AndroidRuntime(12475): 	at android.view.ViewRootImpl$InputStage.onD
W/ActivityManager( 2383):   Force finishing activity com.xabber.androiddev/com.xabber.android.ui.ChatViewer
```

**Comment by aelmahmoudy** [comment]
I noticed now that this happens when I select the text in input chat textbox
