### ISSUE TITLE
All OTR-encrypted messages from Pidgin or Psi+ containing non-ASCII characters are discarded

### ISSUE THREAD

**Issue by nysatrok** [redsolution/xabber-android#385]
The development version discards all OTR-encrypted messages from Pidgin or Psi+ containing non-ASCII characters. Delivery notifications are still sent, though. This issue doesn't occur with the stable version.

**Comment by aelmahmoudy** [comment]
That's true. I wonder if my HTML rendering patch caused this.

**Comment by aelmahmoudy** [comment]
Here's the relevant logcat error:
```
I/System.out(12125): 11:51:41 AM RCV  (1111072848): <message id='purpleeee36e65' type='chat' to='xabberuser@server.com' from='pidginuser@server.com/1c3e9c54-2c2e-4575-994b-c9bbe19b9d88'><active xmlns='http://jabber.org/protocol/chatstates'/><body>?OTR:AAMDOdT/5wuLBjAAAAAAAQAAAAEAAADA65s1wprxbfsXHCBilc/OuQaoAlsRjQJGyVJn/qA4pgLIxiiymv6pz8YyBEaeLOtbHsW9pzWhBGfXafHp+JDuDVutduCI0K7TGRlYUL/WIYI7qRVuLCRwrWAJwH8hkN8YbxUoQdbUjITrNt2gyp+yDkDdHVTZlrF83LmxZhEfXyQ7HDvUEK54KCzRZTjc7p7xuqQzbYt67ZCVSsB72WWsTOqOtJBDJub+8aa/YoErMktbmxmdHrCOPJvKcRn7TfD4AAAAAAAAAAUAAABCQ0CityM6aunUNBAZoaookgP9st+J6lZCx14dUO8h7JpPLTCYM0Bqk40ptRywv8Bp75J2zfGmfRt5zzkpgevP+J50C7tfSVUIhCnIVKn6IYNSCucLKEQAAAAA.</body></message>
W/System.err(12125): xabberuser@server.com/androidrUmSh1VT:pidginuser@server.com
W/System.err(12125): net.java.otr4j.OtrException: java.io.IOException: Unable to read the required amount of bytes from the stream. Expected were 16718 bytes but I could only read 2 bytes.
W/System.err(12125):    at net.java.otr4j.session.Session.handleDataMessage(Session.java:643)
W/System.err(12125):    at net.java.otr4j.session.Session.transformReceiving(Session.java:455)
W/System.err(12125):    at com.xabber.android.data.extension.otr.OTRManager.transformReceiving(OTRManager.java:456)
W/System.err(12125):    at com.xabber.android.data.message.RegularChat.onPacket(RegularChat.java:144)
W/System.err(12125):    at com.xabber.android.data.message.MessageManager.onPacket(MessageManager.java:449)
W/System.err(12125):    at com.xabber.android.data.connection.ConnectionManager.processPacket(ConnectionManager.java:274)
W/System.err(12125):    at com.xabber.android.data.connection.ConnectionThread$20.run(ConnectionThread.java:644)
W/System.err(12125):    at android.os.Handler.handleCallback(Handler.java:733)
W/System.err(12125):    at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err(12125):    at android.os.Looper.loop(Looper.java:136)
W/System.err(12125):    at android.app.ActivityThread.main(ActivityThread.java:5001)
W/System.err(12125):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(12125):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(12125):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
W/System.err(12125):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
W/System.err(12125):    at dalvik.system.NativeStart.main(Native Method)
W/System.err(12125): Caused by: java.io.IOException: Unable to read the required amount of bytes from the stream. Expected were 16718 bytes but I could only read 2 bytes.
W/System.err(12125):    at net.java.otr4j.io.OtrInputStream.checkedRead(OtrInputStream.java:45)
W/System.err(12125):    at net.java.otr4j.io.OtrInputStream.readTlvData(OtrInputStream.java:131)
W/System.err(12125):    at net.java.otr4j.session.Session.handleDataMessage(Session.java:640)
W/System.err(12125):    ... 15 more
```

**Comment by aelmahmoudy** [comment]
From the logcat, the problem is probably from the OTR library.

**Comment by aelmahmoudy** [comment]
I just tested with commit 8a28b947b368069107ccc818e3ec9ad559328267 (the one just before using the new OTR4j library), and cherry-picked my HTML rendering patch, and I can receive non-latin OTR encrypted messages.

**Comment by aelmahmoudy** [comment]
This got fixed (still pending a pull though) in otr4j. Yet there remains a problem when a Xabber user sends an encrypted message to a Pidgin user, the pidgin client then seems to send some response (maybe an acknowledgement?) that Xabber parses as an empty text and displays it as such in the chat view. Actually, this also happens when the pidgin user ends the OTR session.

Screenshot:
![empty_msg](https://cloud.githubusercontent.com/assets/96682/7061024/4e62217a-de94-11e4-8023-d66bf9c88592.JPG)


Here's the relevant logcat:
```
I/com.xabber.android.ui.ChatViewerFragment$5@41c96510( 3367): afterTextChanged
I/System.out( 3367): 07:32:44 AM SENT (1105262824): <message id="mbiHF-32" to="pidginuser@rows.io/5ca25f0f-bd35-4029-8485-4092984f0662" type="chat"><composing xmlns="http://jabber.org/protocol/chatstates" /></message>
I/com.xabber.android.ui.ChatViewerFragment$5@41c96510( 3367): afterTextChanged
I/System.out( 3367): 07:32:45 AM SENT (1105262824): <message id="mbiHF-33" to="pidginuser@rows.io/5ca25f0f-bd35-4029-8485-4092984f0662" type="chat"><body>?OTR:AAMDCoCusznU/+cAAAAAAgAAAAMAAADAMUq3HnN7K/HTfE+6zNA6un1jX/ALhboIbfbotAoyL2HpWgxkI3upl4v2LsjPsLITHu8oUvnV7RVczTyMjBO751x8c8Xo330IeB/Gogv6ulAx5rnrsW5OJOCxkmMTVuQHVQECTYofeQS4rzr06kzqaXdTttbj3IZ0QH9sZL4qKVkrUEItHrnPZQ6LSygMJg551cC2EAUpL2hoFPcuXZZ8BF3yU4XcK0NxMR600khjBO3INM2/qi7+Bowgu/rkZJjiAAAAAAAAAAEAAAACAvWuC4WyJvXRw8qH/otgfyATkDsfmwAAABRtYZFxlIUrbcUswOxlrBmyTKtZCA==.</body><thread>z9Qd2j6EXjD7</thread><active xmlns="http://jabber.org/protocol/chatstates" /><request xmlns="urn:xmpp:receipts" /></message>
I/System.out( 3367): 07:32:46 AM RCV  (1105262824): <message id='purpled32c9fdd' type='chat' to='xabberuser@server.com' from='pidginuser@rows.io/5ca25f0f-bd35-4029-8485-4092984f0662'><active xmlns='http://jabber.org/protocol/chatstates'/><body>?OTR:AAMDOdT/5wqArrMBAAAAAwAAAAMAAADA7bJl/W+zFFEKvwqDfx0Y7zNA+GFvG4dnbMOxGvde1VOC2c30zYbI4hbMzpSc/dcP1WhssI823WQ7sjEPDwHq0JzzKqjI6PZ5WXpUjmUq0mo67UJJL2V9EH/TWFAPzcA7C2Fi2hnCCfL/5Y5e2GZ2YHQHuI74x8676GdRWkz+fcDdywbSLhpwvkREdT1e8CSM5N2Eikgq1q8q9SPX9DXV/6K/TsO/v4/OOwKKCaTaLU79AHHqiHAhnSbaNdrCaII0AAAAAAAAAAEAAAABBLwJOr53QfZ3e6Ivfr4I3d3didwcAAAAFAC/Ft7R+22pA5zYYbSO/ETMyChN.</body></message>
```

**Comment by aelmahmoudy** [comment]
This issue should be closed I think.
