### ISSUE TITLE
ContactListFragment.onItemClick: IllegalStateException

### ISSUE THREAD

**Issue by grigoryfedorov** [redsolution/xabber-android#444]
From Google Play 1.0.7 Android 5.0

> java.lang.IllegalStateException
at com.xabber.android.ui.ContactListFragment.onItemClick(ContactListFragment.java:180)
at android.widget.AdapterView.performItemClick(AdapterView.java:300)
at android.widget.AbsListView.performItemClick(AbsListView.java:1143)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3044)
at android.widget.AbsListView$3.run(AbsListView.java:3833)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5312)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by aileronajay** [comment]
The exception is thrown from the method when the object from the adapter arraylist list is not an instance of either AbstractContact or GroupConfiguration

Is it possible that we are associating an incorrect list with the adapter in the method onCreateView in ContactListFragment.java class?

        View view = inflater.inflate(R.layout.contact_list_fragment, container, false);
        listView = (ListView) view.findViewById(android.R.id.list);
        listView.setOnItemClickListener(this);

**Comment by aileronajay** [comment]
Object object = parent.getAdapter().getItem(position);

is the call by which we get the object in the method ContactListFragment.onItemClick. This method returns an object from the array list in the adapter. Among the various add object calls to the arraylist, baseList, 

we have at line 320 in ContactListAdapter

  baseEntities.add(new AccountTopSeparator(null, null));

also at line 342 , we have

 baseEntities.add(new AccountBottomSeparator(rosterAccount.getAccount(), null));

I wonder if the get call to the arraylist can fetch AccountTopSeparator or AccountBottomSeparator. Neither of them is of type AbstractContact or GroupConfiguration and will potential lead to invalid state exception.

**Comment by grigoryfedorov** [comment]
@aileronajay you're right, but in layouts of AccountTopSeparator and AccountBottomSeparator android:clickable property set to "true". It block onItemClick event. 
I could not reproduce this issue. May be it could happen in some situations.. so I will just remove exeption throw.

**Comment by aileronajay** [comment]
@grigoryfedorov maybe we can add if conditions for instance of  AccountTopSeparator  and AccountBottomSeparator and log (not throw exception) when we get those instances? This way we can know that it is happening and we could open a bug to android source
