### ISSUE TITLE
ChatViewer.onNewIntent: NullPointerException

### ISSUE THREAD

**Issue by grigoryfedorov** [redsolution/xabber-android#445]
From Google Play 1.0.7 Android 4.4
> java.lang.NullPointerException
at com.xabber.android.ui.ChatViewer.onNewIntent(ChatViewer.java:255)
at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1165)
at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2459)
at android.app.ActivityThread.performNewIntents(ActivityThread.java:2472)
at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2481)
at android.app.ActivityThread.access$1600(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1392)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5305)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
at dalvik.system.NativeStart.main(Native Method)

**Comment by grigoryfedorov** [comment]
Fixed in 1.0.8
