### ISSUE TITLE
ContactEditor.editAlias NullPointerException

### ISSUE THREAD

**Issue by grigoryfedorov** [redsolution/xabber-android#461]
From Google Play version 1.0.8

> java.lang.NullPointerException
at com.xabber.android.ui.ContactEditor.editAlias(ContactEditor.java:62)
at com.xabber.android.ui.ContactEditor.onOptionsItemSelected(ContactEditor.java:37)
at android.app.Activity.onMenuItemSelected(Activity.java:2592)
at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:353)
at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:144)
at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
at android.support.v7.internal.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:74)
at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:164)
at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:740)
at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:802)
at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:949)
at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:939)
at android.support.v7.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:187)
at android.widget.AdapterView.performItemClick(AdapterView.java:298)
at android.widget.AbsListView.performItemClick(AbsListView.java:1150)
at android.widget.ListView.performItemClick(ListView.java:4397)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:2985)
at android.widget.AbsListView$1.run(AbsListView.java:3671)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:155)
at android.app.ActivityThread.main(ActivityThread.java:5520)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1058)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
at dalvik.system.NativeStart.main(Native Method)

**Comment by grigoryfedorov** [comment]
Was reproduced following way: 
- add random contact
- remove it
- open contact menu from active chat with this contact
- try "edit alias" 

Fixed in c79dd668694e35435d98a96117f7a43c1f0bf48c - if contact is null, no options menu created (no "edit alias" option, etc0)
