### ISSUE TITLE
connection problem? 

### ISSUE THREAD

**Issue by mis2417** [redsolution/xabber-android#507]
since 1.0.24 (or 1.0.23,i don't know) there is a problem connecting to jabber server. 
password prompt shows up as usual, password is given, icon in taskbar doesn't change to "connected" (full lightbulb), status is "available", and no contacts are shown in list. 

this doesn't happen in 0.9.30 - everything is fine there,so i assume the problem is on xabber side, not the account in question. 

i use two accounts, the other one is gmail, and it works as usual (in beta). 

i also cleaned cache and full application data - no change.

**Comment by txt-file** [comment]
I confirm this issue. It first occured to me in version 1.0.23 and might correlate to the changes in the contact list code between 1.0.22 and 1.0.23.

For me it looks like xabber is cennecting and it tells in the menu that it is "online" but my contact list ist empty.I tried connecting from my notebook, which worked, but i do not see my xabber connection in gajim. The server ist running prosody 0.9.8.

**Comment by kr428** [comment]
Same here. Started at around 1.0.22 and appears on 1.0.25 too. Two accounts, both seem to connect (and show up as "online" in the left side bar menu), but in the status line I see "2 accounts absent", I do not see any connections online and am not able to send any messages. This also happens after purging and re-installing the app. Surprisingly, two offline messages from our server monitor arrived on my local device, same as Xabber asked me whether to activate server-sided message archiving for my corporate XMPP server so I guess in some way it _is_ connecting.

Any way to debug this? Our corporate server runs a recent openfire build, my personal account is on dukgo.com...

**Comment by kr428** [comment]
Adding to that: I managed to restore an old (1.0.21) version from Titanium Backup and indeed this is the last version that does correctly work, and the version I am using so far. Is there any way to help tracking this down?

**Comment by grigoryfedorov** [comment]
@kr428 could you please check these APKs and tell, which of them work correct, and which not? Thank you!
https://www.dropbox.com/s/7fu6ckk5kn9585s/xabber_beta_1.0.21_0f98f20847e9ade24bb1aec747643d8b18900b2b.apk?dl=0
https://www.dropbox.com/s/gshh8pyojk8tkk0/xabber_beta_1.0.21_a7e4a25f8bd61f4a10495c9245cd8592dd037633.apk?dl=0
https://www.dropbox.com/s/po7pqondhrexycn/xabber_beta_1.0.21_d90031c0f130ba65fa74a2cee6d9e58bf4242eda.apk?dl=0

**Comment by mis2417** [comment]
tested all 3 and they work.... buuut i installed on a different phone (stock Samsung G3, rooted).

**Comment by kr428** [comment]
Same here. All three builds work as expected. Phone is LG Optimus 4X HD (p880) on CM11 nightly by the way. Not sure whether this is relevant.

**Comment by grigoryfedorov** [comment]
@mis2417 @kr428 @txt-file unfortunately I still cannot reproduce your issue. 
Could you please test another 3 builds?
https://www.dropbox.com/s/4qhbtyc9ibmazr1/xabber_beta_1.0.21_2d0ff6c956e811a02604f1ab4ee7474a1785a841.apk?dl=0
https://www.dropbox.com/s/sdb5dy2kd55h7f8/xabber_beta_1.0.21_7b220ad858f2e4750b8154a7e86d572c597a7d91.apk?dl=0
https://www.dropbox.com/s/i88x74m1hsmhlke/xabber_beta_1.0.21_bc906738e55930641f84ca3b0bfced696efd740f.apk?dl=0

**Comment by mis2417** [comment]
again, all 3 are ok. 

btw. this one
xabber_beta_1.0.21_2d0ff6c956e811a02604f1ab4ee7474a1785a841.apk
does not display user avatars.

**Comment by mis2417** [comment]
I know! got it to reproduce. 
changing resource name breaks it. as long as it's "androidrandomwhatever" - it's all good. change it to whatever or leave blank - error.

**Comment by mis2417** [comment]
this means that play store beta version works, as long as you don't touch resource name,or clear app data and recreate account

**Comment by kr428** [comment]
Well... I tested the first three .21 builds, each of them worked. Then I updated to the latest version in Play. Outcome: It worked, too, so after configuring everything in .21 and then updating to .25 via Play doesn't seem to cause trouble. Changing the resource name also didn't cause any trouble on my device.

**Comment by mis2417** [comment]
so maybe it was premature. did some more checks. 
clean all data, recreate account in play store beta, without changing resource, works. quit and launch app again - error. 
clean all data, recreate account in play store beta, changing resource, error. 

but. clean all data, recreate account in play store beta, without changing resource, works. quit and launch app again - error. quit and launch app again reverting account completely - works.  when creating account i've changed 3 things: ssl enabled to required, compression to enabled, store history to disabled (i've used these settings in old xabber without error). 
enabling them one by one - enabling compression causes error (for me), it's the type of error thats confusing - no info, seems online but isn't, contacts don't show up. 
messed with resource name and all other settings, it still works, as long as i disable compression.

**Comment by kr428** [comment]
Enabling compression on one account reproducibly triggers this behaviour on 
all accounts here. Currently using .25, compression disabled.

**Comment by txt-file** [comment]
yeah … disabled compression and it is now also working for me again.
(CM11 on htc vision with xabber 1.0.24)

**Comment by grigoryfedorov** [comment]
Thank you, guys. I think I will get compression back to work tomorrow.

**Comment by grigoryfedorov** [comment]
@mis2417 @txt-file @kr428 I think I got this fixed. 
https://www.dropbox.com/s/6y9xb5p4noeddpl/xabber_beta_1.0.25_09c885b9e5523b5079d7b4f24a6d4cfb9a73191e.apk?dl=0
This build should work with compression turned on. Tested on dukgo.com account.

**Comment by kr428** [comment]
Confirmed on my both accounts - thanks loads for the quick fix. ;)

**Comment by tahatauqeer** [comment]
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'taha:5222' failed because java.net.SocketException: failed to connect to taha/192.168.1.4 (port 5222) after 30000ms: isConnected failed: EHOSTUNREACH (No route to host)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:605)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:839)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:364)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at com.xabber.android.data.connection.ConnectionThread.connect(ConnectionThread.java:337)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at com.xabber.android.data.connection.ConnectionThread.access$000(ConnectionThread.java:73)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at com.xabber.android.data.connection.ConnectionThread$2.run(ConnectionThread.java:233)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at com.xabber.android.data.connection.ConnectionThread$18.run(ConnectionThread.java:674)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at java.lang.Thread.run(Thread.java:856)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err: com.xabber.android.data.account.AccountItem@423c0978:admin@taha/Xabber_ERXoY4VS
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err: java.lang.RuntimeException: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'taha:5222' failed because java.net.SocketException: failed to connect to taha/192.168.1.4 (port 5222) after 30000ms: isConnected failed: EHOSTUNREACH (No route to host)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at com.xabber.android.data.connection.ConnectionThread.connect(ConnectionThread.java:343)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at com.xabber.android.data.connection.ConnectionThread.access$000(ConnectionThread.java:73)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at com.xabber.android.data.connection.ConnectionThread$2.run(ConnectionThread.java:233)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at com.xabber.android.data.connection.ConnectionThread$18.run(ConnectionThread.java:674)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at java.lang.Thread.run(Thread.java:856)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err: Caused by: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'taha:5222' failed because java.net.SocketException: failed to connect to taha/192.168.1.4 (port 5222) after 30000ms: isConnected failed: EHOSTUNREACH (No route to host)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:605)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:839)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:364)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err:     at com.xabber.android.data.connection.ConnectionThread.connect(ConnectionThread.java:337)
11-15 08:55:36.164 12552-26558/com.xabber.android.beta W/System.err: 	... 9 more
11-15 08:55:36.164 12552-12552/com.xabber.android.beta I/com.xabber.android.data.account.AccountItem@423c0978:admin@taha/Xabber_ERXoY4VS: onClose 1125895304 - 14, true
11-15 08:55:36.164 12552-12552/com.xabber.android.beta I/com.xabber.android.data.connection.ConnectionManager@4242ccf8: onDisconnect
11-15 08:55:36.174 12552-12552/com.xabber.android.beta I/com.xabber.android.data.notification.NotificationManager@42444530: Notification: 1, ticker: null, sound: null, vibro: 0, light: 0
11-15 08:55:49.528 12552-12552/com.xabber.android.beta I/com.xabber.android.ui.activity.ContactList@42463028: onResume
11-15 08:55:49.588 12552-12552/com.xabber.android.beta I/com.xabber.android.ui.activity.ContactList@42463028: onPause
11-15 08:56:03.112 12552-26559/com.xabber.android.beta W/PingManager: XMPPConnection was not authenticated
11-15 08:56:09.499 12552-12552/com.xabber.android.beta I/com.xabber.android.ui.activity.ContactList@42463028: onResume
11-15 08:56:09.549 12552-12552/com.xabber.android.beta I/com.xabber.android.ui.activity.ContactList@42463028: onPause
11-15 08:56:26.998 12552-12552/com.xabber.android.beta I/com.xabber.android.ui.activity.ContactList@42463028: onResume
11-15 08:56:27.048 12552-12552/com.xabber.android.beta I/com.xabber.android.ui.activity.ContactList@42463028: onPause
11-15 08:56:37.169 12552-12552/com.xabber.android.beta I/com.xabber.android.data.connection.ConnectionThread@432d41e0: NEW connection thread null
11-15 08:56:37.169 12552-12552/com.xabber.android.beta I/com.xabber.android.data.connection.ConnectionManager@4242ccf8: onConnection
11-15 08:56:37.169 12552-12552/com.xabber.android.beta I/com.xabber.android.data.connection.ConnectionThread@432d41e0: start: taha
11-15 08:56:37.179 12552-12552/com.xabber.android.beta I/com.xabber.android.data.notification.NotificationManager@42444530: Notification: 1, ticker: null, sound: null, vibro: 0, light: 0
11-15 08:56:37.189 12552-28032/com.xabber.android.beta I/MemorizingTrustManager: getAppKeyStore(/data/data/com.xabber.android.beta/app_KeyStore/KeyStore.bks) - exception loading file key store
                                                                                 java.io.FileNotFoundException: /data/data/com.xabber.android.beta/app_KeyStore/KeyStore.bks: open failed: ENOENT (No such file or directory)
                                                                                     at libcore.io.IoBridge.open(IoBridge.java:416)
                                                                                     at java.io.FileInputStream.<init>(FileInputStream.java:78)
                                                                                     at de.duenndns.ssl.MemorizingTrustManager.loadAppKeyStore(MemorizingTrustManager.java:338)
                                                                                     at de.duenndns.ssl.MemorizingTrustManager.init(MemorizingTrustManager.java:155)
                                                                                     at de.duenndns.ssl.MemorizingTrustManager.<init>(MemorizingTrustManager.java:133)
                                                                                     at com.xabber.android.data.connection.ConnectionThread.onReady(ConnectionThread.java:197)
                                                                                     at com.xabber.android.data.connection.ConnectionThread.createConnection(ConnectionThread.java:186)
                                                                                     at com.xabber.android.data.connection.ConnectionThread.access$900(ConnectionThread.java:73)
                                                                                     at com.xabber.android.data.connection.ConnectionThread$17.run(ConnectionThread.java:648)
                                                                                     at com.xabber.android.data.connection.ConnectionThread$18.run(ConnectionThread.java:674)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
                                                                                     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                                                     at java.lang.Thread.run(Thread.java:856)
                                                                                  Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                                     at libcore.io.Posix.open(Native Method)
                                                                                     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
                                                                                     at libcore.io.IoBridge.open(IoBridge.java:400)
                                                                                     at java.io.FileInputStream.<init>(FileInputStream.java:78) 
                                                                                     at de.duenndns.ssl.MemorizingTrustManager.loadAppKeyStore(MemorizingTrustManager.java:338) 
                                                                                     at de.duenndns.ssl.MemorizingTrustManager.init(MemorizingTrustManager.java:155) 
                                                                                     at de.duenndns.ssl.MemorizingTrustManager.<init>(MemorizingTrustManager.java:133) 
                                                                                     at com.xabber.android.data.connection.ConnectionThread.onReady(ConnectionThread.java:197) 
                                                                                     at com.xabber.android.data.connection.ConnectionThread.createConnection(ConnectionThread.java:186) 
                                                                                     at com.xabber.android.data.connection.ConnectionThread.access$900(ConnectionThread.java:73) 
                                                                                     at com.xabber.android.data.connection.ConnectionThread$17.run(ConnectionThread.java:648) 
                                                                                     at com.xabber.android.data.connection.ConnectionThread$18.run(ConnectionThread.java:674) 
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442) 
                                                                                     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305) 
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
                                                                                     at java.lang.Thread.run(Thread.java:856) 
11-15 08:56:37.189 12552-12552/com.xabber.android.beta I/com.xabber.android.data.notification.NotificationManager@42444530: Notification: 1, ticker: null, sound: null, vibro: 0, light: 0
11-15 08:56:39.531 12552-12552/com.xabber.android.beta I/com.xabber.android.ui.activity.ContactList@42463028: onResume

**Comment by tahatauqeer** [comment]
@grigoryfedorov help please

**Comment by tahatauqeer** [comment]
@grigoryfedorov app is working on suchat.org but app throws this exception on localhosted openfire server.

**Comment by Maksimovski** [comment]
I have been experiencing the same issue. MemorizingTrustManager is not able to load KeyStore.bks. I testing on Nexus 5X I tried on multiple XMPP servers.

**Comment by tahatauqeer** [comment]
@Maksimovski app was working fine few day ago. but now it is throwing this exception

**Comment by Maksimovski** [comment]
@tahatauqeer yes you are right, actually my colleague was testing the app few days ago, everything was fine. I just contacted him, he said that the app works fine.

**Comment by tahatauqeer** [comment]
@Maksimovski do you know anyone who can help in solving this? because i have to complete my project before next month.

**Comment by Maksimovski** [comment]
@tahatauqeer sorry It seems we will have to handle that by ourselves. We need to focus on SmackException$ConnectionException

**Comment by tahatauqeer** [comment]
@Maksimovski are you on whatsapp? kindly mail me your contact at taha.tauqeer@yahoo.com

**Comment by tahatauqeer** [comment]
@Maksimovski i have solved the problem.

**Comment by Maksimovski** [comment]
@tahatauqeer great, just sent to you my contact info. would be great if you explain the solution  here so that anyone can see that.
