### ISSUE TITLE
:xabber:transformClassesWithDexForBetaDebug

### ISSUE THREAD

**Issue by NoelChew** [redsolution/xabber-android#619]
I am getting this error even after using the 'git submodule init' and 'git submodule update' commands.

Here is the full log:

```
Executing tasks: [:xabber:assembleBetaDebug]

Configuration on demand is an incubating feature.
WARNING: Dependency xpp3:xpp3:1.1.4c is ignored for prodDebug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
WARNING: Dependency xpp3:xpp3:1.1.4c is ignored for prodRelease as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
WARNING: Dependency xpp3:xpp3:1.1.4c is ignored for devDebug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
WARNING: Dependency xpp3:xpp3:1.1.4c is ignored for devRelease as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
WARNING: Dependency xpp3:xpp3:1.1.4c is ignored for vipDebug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
WARNING: Dependency xpp3:xpp3:1.1.4c is ignored for vipRelease as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
WARNING: Dependency xpp3:xpp3:1.1.4c is ignored for betaDebug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
WARNING: Dependency xpp3:xpp3:1.1.4c is ignored for betaRelease as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
:xabber:preBuild UP-TO-DATE
:xabber:preBetaDebugBuild UP-TO-DATE
:xabber:checkBetaDebugManifest
:xabber:preBetaReleaseBuild UP-TO-DATE
:xabber:preDevDebugBuild UP-TO-DATE
:xabber:preDevReleaseBuild UP-TO-DATE
:xabber:preProdDebugBuild UP-TO-DATE
:xabber:preProdReleaseBuild UP-TO-DATE
:xabber:preVipDebugBuild UP-TO-DATE
:xabber:preVipReleaseBuild UP-TO-DATE
:xabber:MemorizingTrustManager:preBuild UP-TO-DATE
:xabber:MemorizingTrustManager:preReleaseBuild UP-TO-DATE
:xabber:MemorizingTrustManager:compileReleaseNdk UP-TO-DATE
:xabber:MemorizingTrustManager:compileLint
:xabber:MemorizingTrustManager:copyReleaseLint UP-TO-DATE
:xabber:MemorizingTrustManager:checkReleaseManifest
:xabber:MemorizingTrustManager:preDebugAndroidTestBuild UP-TO-DATE
:xabber:MemorizingTrustManager:preDebugBuild UP-TO-DATE
:xabber:MemorizingTrustManager:preDebugUnitTestBuild UP-TO-DATE
:xabber:MemorizingTrustManager:preReleaseUnitTestBuild UP-TO-DATE
:xabber:MemorizingTrustManager:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:xabber:MemorizingTrustManager:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:xabber:MemorizingTrustManager:prepareReleaseDependencies
:xabber:MemorizingTrustManager:compileReleaseAidl UP-TO-DATE
:xabber:MemorizingTrustManager:compileReleaseRenderscript UP-TO-DATE
:xabber:MemorizingTrustManager:generateReleaseBuildConfig UP-TO-DATE
:xabber:MemorizingTrustManager:generateReleaseAssets UP-TO-DATE
:xabber:MemorizingTrustManager:mergeReleaseAssets UP-TO-DATE
:xabber:MemorizingTrustManager:generateReleaseResValues UP-TO-DATE
:xabber:MemorizingTrustManager:generateReleaseResources UP-TO-DATE
:xabber:MemorizingTrustManager:mergeReleaseResources UP-TO-DATE
:xabber:MemorizingTrustManager:processReleaseManifest UP-TO-DATE
:xabber:MemorizingTrustManager:processReleaseResources UP-TO-DATE
:xabber:MemorizingTrustManager:generateReleaseSources UP-TO-DATE
:xabber:MemorizingTrustManager:compileReleaseJavaWithJavac UP-TO-DATE
:xabber:MemorizingTrustManager:extractReleaseAnnotations UP-TO-DATE
:xabber:MemorizingTrustManager:mergeReleaseProguardFiles UP-TO-DATE
:xabber:MemorizingTrustManager:packageReleaseRenderscript UP-TO-DATE
:xabber:MemorizingTrustManager:packageReleaseResources UP-TO-DATE
:xabber:MemorizingTrustManager:processReleaseJavaRes UP-TO-DATE
:xabber:MemorizingTrustManager:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:xabber:MemorizingTrustManager:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:xabber:MemorizingTrustManager:mergeReleaseJniLibFolders UP-TO-DATE
:xabber:MemorizingTrustManager:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:xabber:MemorizingTrustManager:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:xabber:MemorizingTrustManager:bundleRelease UP-TO-DATE
:xabber:emojicon:preBuild UP-TO-DATE
:xabber:emojicon:preReleaseBuild UP-TO-DATE
:xabber:emojicon:compileReleaseNdk UP-TO-DATE
:xabber:emojicon:compileLint
:xabber:emojicon:copyReleaseLint UP-TO-DATE
:xabber:emojicon:checkReleaseManifest
:xabber:emojicon:preDebugAndroidTestBuild UP-TO-DATE
:xabber:emojicon:preDebugBuild UP-TO-DATE
:xabber:emojicon:preDebugUnitTestBuild UP-TO-DATE
:xabber:emojicon:preReleaseUnitTestBuild UP-TO-DATE
:xabber:emojicon:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:xabber:emojicon:prepareReleaseDependencies
:xabber:emojicon:compileReleaseAidl UP-TO-DATE
:xabber:emojicon:compileReleaseRenderscript UP-TO-DATE
:xabber:emojicon:generateReleaseBuildConfig UP-TO-DATE
:xabber:emojicon:generateReleaseAssets UP-TO-DATE
:xabber:emojicon:mergeReleaseAssets UP-TO-DATE
:xabber:emojicon:generateReleaseResValues UP-TO-DATE
:xabber:emojicon:generateReleaseResources UP-TO-DATE
:xabber:emojicon:mergeReleaseResources UP-TO-DATE
:xabber:emojicon:processReleaseManifest UP-TO-DATE
:xabber:emojicon:processReleaseResources UP-TO-DATE
:xabber:emojicon:generateReleaseSources UP-TO-DATE
:xabber:emojicon:compileReleaseJavaWithJavac UP-TO-DATE
:xabber:emojicon:extractReleaseAnnotations UP-TO-DATE
:xabber:emojicon:mergeReleaseProguardFiles UP-TO-DATE
:xabber:emojicon:packageReleaseRenderscript UP-TO-DATE
:xabber:emojicon:packageReleaseResources UP-TO-DATE
:xabber:emojicon:processReleaseJavaRes UP-TO-DATE
:xabber:emojicon:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:xabber:emojicon:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:xabber:emojicon:mergeReleaseJniLibFolders UP-TO-DATE
:xabber:emojicon:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:xabber:emojicon:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:xabber:emojicon:bundleRelease UP-TO-DATE
:xabber:otr4j:compileJava UP-TO-DATE
:xabber:otr4j:processResources UP-TO-DATE
:xabber:otr4j:classes UP-TO-DATE
:xabber:otr4j:jar UP-TO-DATE
:xabber:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:xabber:prepareComAndroidSupportDesign2311Library UP-TO-DATE
:xabber:prepareComAndroidSupportRecyclerviewV72311Library UP-TO-DATE
:xabber:prepareComAndroidSupportSupportV132311Library UP-TO-DATE
:xabber:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:xabber:prepareComMelnykovFloatingactionbutton120Library UP-TO-DATE
:xabber:prepareComSoundcloudAndroidAndroidCrop101Library UP-TO-DATE
:xabber:prepareDeHdodenhofCircleimageview122Library UP-TO-DATE
:xabber:prepareXabberAndroidXabberEmojiconUnspecifiedLibrary UP-TO-DATE
:xabber:prepareXabberAndroidXabberMemorizingTrustManagerUnspecifiedLibrary UP-TO-DATE
:xabber:prepareBetaDebugDependencies
:xabber:compileBetaDebugAidl UP-TO-DATE
:xabber:compileBetaDebugRenderscript UP-TO-DATE
:xabber:generateBetaDebugBuildConfig UP-TO-DATE
:xabber:generateBetaDebugAssets UP-TO-DATE
:xabber:mergeBetaDebugAssets UP-TO-DATE
:xabber:generateBetaDebugResValues UP-TO-DATE
:xabber:generateBetaDebugResources UP-TO-DATE
:xabber:mergeBetaDebugResources UP-TO-DATE
:xabber:processBetaDebugManifest UP-TO-DATE
:xabber:processBetaDebugResources UP-TO-DATE
:xabber:generateBetaDebugSources UP-TO-DATE
:xabber:compileBetaDebugJavaWithJavac
Note: Version 0.88.0 of Realm is now available: http://static.realm.io/downloads/java/latest
Note: Processing class BlockedContact
Note: Processing class BlockedContactsForAccount
Note: Creating DefaultRealmModule
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:xabber:compileBetaDebugNdk UP-TO-DATE
:xabber:compileBetaDebugSources
:xabber:transformClassesWithDexForBetaDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
    at com.android.dx.command.dexer.Main.processClass(Main.java:752)
    at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718)
    at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
    at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1645)
    at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
    at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
    at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
    at com.android.dx.command.dexer.Main.processOne(Main.java:672)
    at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
    at com.android.dx.command.dexer.Main.run(Main.java:277)
    at com.android.dx.command.dexer.Main.main(Main.java:245)
    at com.android.dx.command.Main.main(Main.java:106)
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
    at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
    at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
    at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
    at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
    at com.android.dx.command.dexer.Main.parseClass(Main.java:764)
    at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
    at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)
    at com.android.dx.command.dexer.Main.processClass(Main.java:749)
    ... 12 more
1 error; aborting


 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xabber:transformClassesWithDexForBetaDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 58.902 secs
```

**Comment by grigoryfedorov** [comment]
Hi! Try to use JDK 7

**Comment by sagarnayak** [comment]
i typed java -version to my terminal in mac and i got 1.8.0 .still i get this error in android studio.
