### ISSUE TITLE
services such as Olark raise an exception in HttpFileUploadManager.java on HttpFileUploadManager.discoverSupport(...)

### ISSUE THREAD

**Issue by nighthawk2290** [redsolution/xabber-android#651]
06-01 20:18:15.647 21490-21571/com.xabber.android.beta I/System.out: 08:18:15 PM RECV (0): <iq from='im.olark.com' to='zzzz@olark.com/Xabber_zzzzzzzzz' type='result' id='zzzzzzz'><query xmlns='http://jabber.org/protocol/disco#info'/><identity category='account' type='registered' name='Olark Account'/><feature var='http://jabber.org/protocol/disco#info'/></iq>
06-01 20:18:15.657 21490-21613/com.xabber.android.beta E/AndroidRuntime: FATAL EXCEPTION: Thread to check for zzzz@olark.com/Xabber_zzzzzzzzz
                                                                         Process: com.xabber.android.beta, PID: 21490
                                                                         java.lang.ClassCastException: org.jivesoftware.smack.packet.UnparsedIQ cannot be cast to org.jivesoftware.smackx.disco.packet.DiscoverInfo
                                                                             at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:535)
                                                                             at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:500)
                                                                             at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.findServices(ServiceDiscoveryManager.java:734)
                                                                             at com.xabber.android.data.extension.httpfileupload.HttpFileUploadManager.discoverSupport(HttpFileUploadManager.java:203)
                                                                             at com.xabber.android.data.extension.httpfileupload.HttpFileUploadManager.access$100(HttpFileUploadManager.java:40)
                                                                             at com.xabber.android.data.extension.httpfileupload.HttpFileUploadManager$3.run(HttpFileUploadManager.java:220)

---

To solve that on my local copy here, I've added on HttpFileUploadManager.java line 203 -- try ... catch  -- to avoid that exception...

The problem was raised on Olark service,. on other services, I didn't see that it exists...

**Comment by andrewnenakhov** [comment]
@Str4tocaster since we started fixing olark, check this out too

**Comment by Str4tocaster** [comment]
Fixed in https://github.com/redsolution/xabber-android/commit/792f3c0645e979bf944323469f695abc605eab75
