### ISSUE TITLE
Crash, possibly avatar/vCard related

### ISSUE THREAD

**Issue by madduck** [redsolution/xabber-android#658]
Hello,

I just installed Xabber Dev for the first time (from F-Droid, version 1.0.74) and connected to my existing account, which works just fine with yaxim, Beem, ChatSecure, BitlBee, and Thunderbird.

Unfortunately, as soon as I connect, Xabber crashes. I think it's related to this backtrace I find in the logs:

```
07-10 13:39:32.448 24910 24910 D AndroidRuntime: Shutting down VM
07-10 13:39:32.448 24910 24910 E AndroidRuntime: FATAL EXCEPTION: main
07-10 13:39:32.448 24910 24910 E AndroidRuntime: Process: com.xabber.androiddev, PID: 24910
07-10 13:39:32.448 24910 24910 E AndroidRuntime: java.lang.IllegalArgumentException: bad base-64
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at android.util.Base64.decode(Base64.java:161)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at android.util.Base64.decode(Base64.java:136)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at android.util.Base64.decode(Base64.java:118)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at org.jivesoftware.smack.util.stringencoder.android.AndroidBase64Encoder.decode(AndroidBase64Encoder.java:41)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at org.jivesoftware.smack.util.stringencoder.Base64.decode(Base64.java:86)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at org.jivesoftware.smackx.vcardtemp.packet.VCard.getAvatar(VCard.java:454)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at org.jivesoftware.smackx.vcardtemp.packet.VCard.getAvatarHash(VCard.java:506)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at com.xabber.android.data.extension.vcard.VCardManager.onVCardReceived(VCardManager.java:201)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at com.xabber.android.data.extension.vcard.VCardManager.access$300(VCardManager.java:62)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at com.xabber.android.data.extension.vcard.VCardManager$4$1.run(VCardManager.java:331)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7229)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
07-10 13:39:32.448 24910 24910 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)
07-10 13:39:32.458 30311 31411 W VirtualScreenManagerService: moveTaskBackToDisplayIfNeeded(): The task has more than one activity
07-10 13:39:32.458 30311 31411 W ActivityManager:   Force finishing activity com.xabber.androiddev/com.xabber.android.ui.preferences.AccountList
```

I've tried disabling avatars (Settings → Contact list → Show account panel and Show avatars), but that has no effect.

How can I debug this further and determine where the alleged false base64 comes from?

**Comment by climf** [comment]
Try setting avatar to a 1x1 image (single pixel).

**Comment by andrewnenakhov** [comment]
@madduck does this still happen with current Xabber Beta (2.0.2)?
