### ISSUE TITLE
Crashes when receiving message in MUC

### ISSUE THREAD

**Issue by bostrt** [redsolution/xabber-android#663]
When I receive a new message in a multi-user-chat, Xabber is crashing with exception below. Only happens when I have the MUC chat window open.

Affects Xabber Beta 1.0.74

```
09-16 20:02:37.255  9920  9920 D AndroidRuntime: Shutting down VM
09-16 20:02:37.258  9920  9920 E AndroidRuntime: FATAL EXCEPTION: main
09-16 20:02:37.258  9920  9920 E AndroidRuntime: Process: com.xabber.android.beta, PID: 9920
09-16 20:02:37.258  9920  9920 E AndroidRuntime: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(pri=0 contentView=com.xabber.android.beta/0x1090086 vibrate=default sound=content://settings/system/notification_sound defaults=0x6 flags=0x1 color=0x00000000 vis=PRIVATE)
09-16 20:02:37.258  9920  9920 E AndroidRuntime:    at android.app.NotificationManager.notify(NotificationManager.java:222)
09-16 20:02:37.258  9920  9920 E AndroidRuntime:    at android.app.NotificationManager.notify(NotificationManager.java:194)
09-16 20:02:37.258  9920  9920 E AndroidRuntime:    at com.xabber.android.data.notification.NotificationManager.notify(NotificationManager.java:448)
09-16 20:02:37.258  9920  9920 E AndroidRuntime:    at com.xabber.android.data.notification.NotificationManager.onCurrentChatMessageNotification(NotificationManager.java:496)
09-16 20:02:37.258  9920  9920 E AndroidRuntime:    at com.xabber.android.data.message.AbstractChat.newMessage(AbstractChat.java:440)
09-16 20:02:37.258  9920  9920 E AndroidRuntime:    at com.xabber.android.data.extension.muc.RoomChat.onPacket(RoomChat.java:256)
09-16 20:02:37.258  9920  9920 E AndroidRuntime:    at com.xabber.android.data.message.MessageManager.onPacket(MessageManager.java:593)
09-16 20:02:37.258  9920  9920 E AndroidRuntime:    at com.xabber.android.data.connection.ConnectionManager.processPacket(ConnectionManager.java:265)
09-16 20:02:37.258  9920  9920 E AndroidRuntime:    at com.xabber.android.data.connection.ConnectionThread$16.run(ConnectionThread.java:604)
09-16 20:02:37.258  9920  9920 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:746)
09-16 20:02:37.258  9920  9920 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:95)
09-16 20:02:37.258  9920  9920 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
09-16 20:02:37.258  9920  9920 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5491)
09-16 20:02:37.258  9920  9920 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
09-16 20:02:37.258  9920  9920 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
09-16 20:02:37.258  9920  9920 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
09-16 20:02:37.264  1469  2676 W ActivityManager:   Force finishing activity com.xabber.android.beta/com.xabber.android.ui.activity.ChatViewer
```

**Comment by andrewnenakhov** [comment]
Closing, since we're going to replace MUC protocol with new superior group chat protocol.

**Comment by msva** [comment]
Is it any documentation (or, even better, XEP number) about that magic "new superior group chat protocol"?

**Comment by andrewnenakhov** [comment]
@msva it's not yet final, though web version of Xabber already works with it quite well. We'll submit it to XSF once we'll think it is mature enough. If you are interested to read it, email us info@xabber.com we'll send you an invitation to a Google doc with working data.
