### ISSUE TITLE
xabber connection error plz help.

### ISSUE THREAD

**Issue by lalalaho** [redsolution/xabber-android#687]
I have a LG V20.

xabber don't working 
only connection error

please check this.

and other people have same problem.

**Comment by casperklein** [comment]
Two things to check:
- Did you try with a different jabber server?
- As you don't write which Xabber version you are using, you could try the latest development version (build it yourself, not the beta from the store)

**Comment by lalalaho** [comment]
I used version 4.2 and 4.5. but I still can not connect.

But IM+ working on server.
So, I using IM+ now.

IM+'s ux too terrible.
I wanna using xabber.

**Comment by grigoryfedorov** [comment]
@lalalaho you can try latest Beta (1.0.173) from Google Play.

**Comment by lalalaho** [comment]
I checked updating Xabber 3.7 and Xabber Beta.
And I tried both.

But it does not work.

My phone is LG V20 which is used in Korea. And the phone is using Android OS.7.0.1.
I think LG does not update the Android OS.

I have captured errors in 3.7 and beta versions. Both have the same error.

Thank you for your help.

This is error log.

org.jivesoftware.smack.SmackException: javax.net.ssl.SSLHandshakeException: Handshake failed
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(Unknown Source)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(Unknown Source)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:761)
Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:429)
	at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:682)
	at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:644)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.initReaderAndWriter(Unknown Source)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(Unknown Source)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1200(Unknown Source)
	... 4 more
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x70c4883880: Failure in SSL library, usually a protocol error
error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (external/boringssl/src/ssl/s3_pkt.c:610 0x70c1e20d20:0x00000001)
error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (external/boringssl/src/ssl/s3_clnt.c:764 0x70db997095:0x00000000)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
	... 9 more

**Comment by andrewnenakhov** [comment]
@lalalaho please do the following:
1) install latest Xabber Beta from Google Play
2) enable debug logging
3) try connecting to account
4) if it fails, attach logs here (if not - close issue)

**Comment by Tristan1234** [comment]
I have the same problem. Tried the beta build on 11/6/2017 and the normal one. Exact same error as listed above. Been using this for so long and after updating this happend. RIP pls fix
org.jivesoftware.smack.SmackException: javax.net.ssl.SSLHandshakeException: Handshake failed
at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(Unknown Source)
at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(Unknown Source)
at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(Unknown Source)
at java.lang.Thread.run(Thread.java:761)
Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:429)
at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:682)
at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:644)
at org.jivesoftware.smack.tcp.XMPPTCPConnection.initReaderAndWriter(Unknown Source)
at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(Unknown Source)
at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1200(Unknown Source)
... 4 more
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x70c4883880: Failure in SSL library, usually a protocol error
error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (external/boringssl/src/ssl/s3_pkt.c:610 0x70c1e20d20:0x00000001)
error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (external/boringssl/src/ssl/s3_clnt.c:764 0x70db997095:0x00000000)
at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)

**Comment by Tristan1234** [comment]
ok so here is the debug log ill attach it to this comment I changed the server I connect to to server.com and my username to username. Just for you know.
[XabberBeta_2.0.2(356)_2017-06-11_00-38-02.txt](https://github.com/redsolution/xabber-android/files/1066147/XabberBeta_2.0.2.356._2017-06-11_00-38-02.txt)

**Comment by klayman** [comment]
It looks like xabber relies on the TLS 1.0/1.1 and the older ciphers, which are now disabled on some servers due to security concerns. So if one have access to the XMPP/Jabber server configs, it's possible to temporary enable the older protocols to let xabber to connect. But the better approach to fix the SSL handshake error would be to implement the more secure protocols in xabber.

**Comment by andrewnenakhov** [comment]
@klayman you got it all wrong. User is reporting broken certificate problem while using legacy SSL. We do not plan to fix it, since this connection method is obsolete and wrong. 

Xabber supports latest TLS, we just added back older SSL because of some ultra unhappy users who where stuck on poorly maintained servers with Legacy SSL. However, supporting both legacy SSLs and broken certificates is not what we have resources to do.

**Comment by klayman** [comment]
@andrewnenakhov Perhaps. But I experience the SSL handshake errors in both stable and beta xabber, when I have

        protocol_options:
          - "no_sslv2"
          - "no_sslv3"
          - "no_tlsv1"
          - "no_tlsv1_1"
          - "cipher_server_preference"
        ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"

in my ejabberd config. Commenting out the tls and cipher lines eliminates the problem.

**Comment by lalalaho** [comment]
Thanks for update.
Now Xabber is Working on android 7.0

**Comment by andrewnenakhov** [comment]
Happy for you )

**Comment by immy4love** [comment]
I have same issue
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(Unknown Source)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(Unknown Source)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(Unknown Source)
	at com.xabber.android.data.connection.ConnectionThread.connectAndLogin(Unknown Source)
	at com.xabber.android.data.connection.ConnectionThread$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:761)

**Comment by pboettcher** [comment]
I am getting this error when I receive a HTTPS-link to a picture from a website other than jabber server. This is definitely not normal.

**Comment by andrewnenakhov** [comment]
@pboettcher these errors are not related to https
