### ISSUE TITLE
Log Manager Error

### ISSUE THREAD

**Issue by Kishore1224** [redsolution/xabber-android#714]
Hi 
Can you tell me the solution for this error..

 D/KeyguardUpdateMonitor: sendKeyguardVisibilityChanged(true)
04-24 14:29:42.896 27014-27014/com.xabber.android E/AndroidRuntime: FATAL EXCEPTION: main
  Process: com.xabber.android, PID: 27014 java.lang.NoClassDefFoundError: org.jivesoftware.smack.debugger.ReflectionDebuggerFactory
 at org.jivesoftware.smack.SmackConfiguration.<clinit>(SmackConfiguration.java:65)
 at com.xabber.android.data.log.LogManager.onSettingsChanged(LogManager.java:62)
 at com.xabber.android.data.log.LogManager.<init>(LogManager.java:54)
 at com.xabber.android.data.log.LogManager.getInstance(LogManager.java:44)
at com.xabber.android.data.Application.addManagers(Application.java:310)
at com.xabber.android.data.Application.onCreate(Application.java:301)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
at android.app.ActivityThread.access$1600(ActivityThread.java:175)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
 at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5602)
at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:515)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
 at dalvik.system.NativeStart.main(Native Method)
04-24 14:29:42.896 2465-2476/? W/ActivityManager:   Force finishing activity com.xabber.android/.ui.activity.ContactListActivity

**Comment by Human** [comment]
I was going to diagnose and fix a bug with the app, and I ran into this as well when running it.

**Comment by andrewnenakhov** [comment]
@Str4tocaster take a look please
