### ISSUE TITLE
No supported and enabled SASL Mechanism provided by server (DIGEST-MD5)

### ISSUE THREAD

**Issue by kapitan-iglu** [redsolution/xabber-android#726]
Hi,
I can't connect to XMPP server because of this error:
```
org.jivesoftware.smack.SmackException: No supported and enabled SASL Mechanism provided by server. Server announced mechanisms: [DIGEST-MD5]. Registerd SASL mechanisms with Smack: [SASL Mech: SCRAM-SHA-1-PLUS, Prio: 100, SASL Mech: SCRAM-SHA-1, Prio: 110, SASL Mech: DIGEST-MD5, Prio: 210, SASL Mech: PLAIN, Prio: 410, SASL Mech: X-OAUTH2, Prio: 410, SASL Mech: ANONYMOUS, Prio: 500, SASL Mech: EXTERNAL, Prio: 510]. Enabled SASL mechansisms for this connection: null. Blacklisted SASL mechanisms: [DIGEST-MD5, SCRAM-SHA-1-PLUS].
	at org.jivesoftware.smack.SASLAuthentication.selectMechanism(Unknown Source)
	at org.jivesoftware.smack.SASLAuthentication.authenticate(Unknown Source)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.loginInternal(Unknown Source)
	at org.jivesoftware.smack.AbstractXMPPConnection.login(Unknown Source)
	at org.jivesoftware.smack.AbstractXMPPConnection.login(Unknown Source)
	at com.xabber.android.data.connection.ConnectionThread.connectAndLogin(Unknown Source)
	at com.xabber.android.data.connection.ConnectionThread$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:818)
```
I want to know more details about that:
* Who and why blacklisted DIGEST-MD5 mechanism? 
* Blacklist is stored in Xabber client or in 3rd party lib (smack/android)?
* How can I remove DIGEST-MD5 from blacklist? (I know it is not good idea, but I have no chance to 
change server configuration).

Thanks!

**Comment by Str4tocaster** [comment]
@kapitan-iglu DIGEST-MD5 was blacklisted because it was have some issue in Smack implementation. Now issue was fixed and this mechanism available again in https://github.com/redsolution/xabber-android/commit/47e8fccbf308cf5a266884ba045f18db3796a71b. Please check it out.

**Comment by kapitan-iglu** [comment]
Thanks!
In which beta version it will be included?
Or are there any nightly builds available so I can test earlier?

**Comment by kapitan-iglu** [comment]
Just updated beta to 2.0.2 (360) and its working as expected. Thanx again!
