### ISSUE TITLE
Cannot connect to Openfire

### ISSUE THREAD

**Issue by Dobromyr** [redsolution/xabber-android#730]
Xabber Beta 2.0.2 (356)

I try connect to server and I receive an error:

```
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(Unknown Source)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(Unknown Source)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(Unknown Source)
	at com.xabber.android.data.connection.ConnectionThread.connectAndLogin(Unknown Source)
	at com.xabber.android.data.connection.ConnectionThread$1.run(Unknown Source)
	at java.lang.Thread.run(thread.java:818)
```

In openfire log:
```
2017.06.06 12:26:10 WARN  [socket_c2s-thread-23]: org.jivesoftware.openfire.nio.ConnectionHandler - Closing connection due to exception in session: (0x0000F602: nio socket, server, /46.211.127.10:22232 => /xxx.xxx.xxx.xxx:5222)
org.apache.mina.filter.codec.ProtocolDecoderException: org.jivesoftware.openfire.nio.XMLNotWellFormedException: Character is invalid in:  (Hexdump: 16 03 01 00 BD 01 00 00 B9 03 03 6E 91 D5 DB D6 47 12 BE 4F 54 14 96 14 E4 72 BD 9F 1B A5 C0 7C 67 92 1E 07 7E B1 44 37 8F 2E B0 00 00 2C C0 2B C0 2C C0 2F C0 30 00 9E 00 9F C0 09 C0 0A C0 13 C0 14 00 33 00 39 00 32 00 38 C0 07 C0 11 00 9C 00 9D 00 2F 00 35 00 05 00 FF 01 00 00 64 00 0B 00 04 03 00 01 02 00 0A 00 34 00 32 00 0E 00 0D 00 19 00 0B 00 0C 00 18 00 09 00 0A 00 16 00 17 00 08 00 06 00 07 00 14 00 15 00 04 00 05 00 12 00 13 00 01 00 02 00 03 00 0F 00 10 00 11 00 0D 00 20 00 1E 06 01 06 02 06 03 05 01 05 02 05 03 04 01 04 02 04 03 03 01 03 02 03 03 02 01 02 02 02 03)
```

DNS resolve server name
From PC and IM+ messenger - all good

**Comment by travnewmatic** [comment]
i'm having the same issue!  very curious to hear a resolution to this.

**Comment by Str4tocaster** [comment]
@Dobromyr Piece that you attached not enough to recognize issue. Can you send full log?

**Comment by ionty** [comment]
Same error for me. Here is my log:

```
2017-06-20_09-01-21 D/AccountItem: user@mydomain.example/android0kUmJa14ï¹• connect
2017-06-20_09-01-21 D/AccountItem: user@mydomain.example/android0kUmJa14ï¹• updateState. prev offline new connecting
2017-06-20_09-01-21 D/ConnectionThread: user@mydomain.example/android0kUmJa14ï¹• Connection thread is finished, creating new one...
2017-06-20_09-01-21 D/ConnectionThread: user@mydomain.example/android0kUmJa14ï¹• Creating new connection thread
2017-06-20_09-01-21 D/ConnectionThread: user@mydomain.example/android0kUmJa14ï¹• Connection thread is new, starting...
2017-06-20_09-01-21 D/ConnectionThread: user@mydomain.example/android0kUmJa14ï¹• Use DNS Java resolver
2017-06-20_09-01-21 D/ConnectionThread: user@mydomain.example/android0kUmJa14ï¹• Trying to connect and login...
2017-06-20_09-01-21 D/AccountItem: user@mydomain.example/android0kUmJa14ï¹• updateState. prev connecting new connecting
2017-06-20_09-01-21 D/org.jivesoftware.smack.tcp.XMPPTCPConnectionï¹• Trying to establish TCP connection to /<IP-Address> at port 5222
2017-06-20_09-01-21 D/com.xabber.android.service.XabberService@84f03c4ï¹• changeForeground
2017-06-20_09-01-21 D/com.xabber.android.data.notification.NotificationManager@c51573dï¹• updatePersistentNotification account user@mydomain.example/android0kUmJa14 state connecting
2017-06-20_09-01-21 D/com.xabber.android.data.notification.NotificationManager@c51573dï¹• Notification: 1, sound: null, vibro: 0, light: 0, ticker: ***
2017-06-20_09-01-21 D/AccountItem: user@mydomain.example/android0kUmJa14ï¹• connect
2017-06-20_09-01-21 D/AccountItem: user@mydomain.example/android0kUmJa14ï¹• updateState. prev connecting new connecting
2017-06-20_09-01-21 D/ConnectionThread: user@mydomain.example/android0kUmJa14ï¹• Connection thread is running already
2017-06-20_09-01-21 D/ReconnectionManagerï¹• user@mydomain.example/android0kUmJa14 not authenticated. already in progress. reset time. attempt 0
2017-06-20_09-01-21 W/ConnectionThread: user@mydomain.example/android0kUmJa14: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(Unknown Source)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(Unknown Source)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(Unknown Source)
	at com.xabber.android.data.connection.ConnectionThread.connectAndLogin(Unknown Source)
	at com.xabber.android.data.connection.ConnectionThread$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:761)

2017-06-20_09-01-21 E/ConnectionThread: user@mydomain.example/android0kUmJa14ï¹• org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed
2017-06-20_09-01-21 E/ConnectionThread: user@mydomain.example/android0kUmJa14ï¹• org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(Unknown Source)
2017-06-20_09-01-21 E/ConnectionThread: user@mydomain.example/android0kUmJa14ï¹• org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(Unknown Source)
2017-06-20_09-01-21 E/ConnectionThread: user@mydomain.example/android0kUmJa14ï¹• org.jivesoftware.smack.AbstractXMPPConnection.connect(Unknown Source)
2017-06-20_09-01-21 E/ConnectionThread: user@mydomain.example/android0kUmJa14ï¹• com.xabber.android.data.connection.ConnectionThread.connectAndLogin(Unknown Source)
2017-06-20_09-01-21 E/ConnectionThread: user@mydomain.example/android0kUmJa14ï¹• com.xabber.android.data.connection.ConnectionThread$1.run(Unknown Source)
2017-06-20_09-01-21 E/ConnectionThread: user@mydomain.example/android0kUmJa14ï¹• java.lang.Thread.run(Thread.java:761)
2017-06-20_09-01-21 D/ConnectionThread: user@mydomain.example/android0kUmJa14ï¹• There was no successful connection, disabling account
2017-06-20_09-01-21 D/com.xabber.android.data.notification.NotificationManager@c51573dï¹• Notification: 18, sound: content://media/internal/audio/media/15, vibro: 0, light: 4, ticker: ***
2017-06-20_09-01-21 D/ConnectionThread: user@mydomain.example/android0kUmJa14ï¹• Connection thread finished
2017-06-20_09-01-21 D/AccountItem: user@mydomain.example/android0kUmJa14ï¹• disconnect
2017-06-20_09-01-21 D/AccountItem: user@mydomain.example/android0kUmJa14ï¹• already disconnected

```
I removed everything related to other servers. Please let me know if you need more information.

**Comment by oxoWrk** [comment]
@ionty Maybe the reason in this:
`2017-06-20_09-01-21 D/org.jivesoftware.smack.tcp.XMPPTCPConnectionï¹• Trying to establish TCP connection to /<IP-Address> at port 5222`

**Comment by ionty** [comment]
@oxoWrk Sure it is, but why can't it connect? There are other connections to this server and this port from other devices, e.g. my laptop.

**Comment by Dobromyr** [comment]
HI!
Full log (i change domen name and IP): 

```
2017-06-21_09-51-06 D/NetworkManager﹕ Active network info: [type: MOBILE[HSPA+] - MOBILE, state: CONNECTED/CONNECTED, reason: connected, extra: www.kyivstar.net, roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]
2017-06-21_09-51-06 D/NetworkManager﹕ onAvailable
2017-06-21_09-51-06 D/ConnectionManager﹕ connectAll
2017-06-21_09-51-09 D/AccountItem: username@myjabber.com/Xabber_kavfIM1a﹕ connect
2017-06-21_09-51-09 D/AccountItem: username@myjabber.com/Xabber_kavfIM1a﹕ updateState. prev offline new connecting
2017-06-21_09-51-09 D/ConnectionThread: username@myjabber.com/Xabber_kavfIM1a﹕ Connection thread is finished, creating new one...
2017-06-21_09-51-09 D/ConnectionThread: username@myjabber.com/Xabber_kavfIM1a﹕ Creating new connection thread
2017-06-21_09-51-09 D/ConnectionThread: username@myjabber.com/Xabber_kavfIM1a﹕ Connection thread is new, starting...
2017-06-21_09-51-09 D/ConnectionThread: username@myjabber.com/Xabber_kavfIM1a﹕ Use DNS Java resolver
2017-06-21_09-51-09 D/ConnectionThread: username@myjabber.com/Xabber_kavfIM1a﹕ Trying to connect and login...
2017-06-21_09-51-09 D/AccountItem: username@myjabber.com/Xabber_kavfIM1a﹕ updateState. prev connecting new connecting
2017-06-21_09-51-09 D/org.c.a.z@9536a82﹕ cache: NXDOMAIN
2017-06-21_09-51-09 D/org.jivesoftware.smack.util.DNSUtil﹕ Could not resolve DNS SRV resource records for _xmpp-client._tcp.myjabber.com. Consider adding those.
2017-06-21_09-51-09 D/com.xabber.android.service.XabberService@32e4f259﹕ changeForeground
2017-06-21_09-51-09 D/com.xabber.android.data.notification.NotificationManager@25dd1cd7﹕ updatePersistentNotification account username@myjabber.com/Xabber_kavfIM1a state connecting
2017-06-21_09-51-09 D/com.xabber.android.data.notification.NotificationManager@25dd1cd7﹕ Notification: 1, sound: null, vibro: 0, light: 0, ticker: ***
2017-06-21_09-51-09 D/org.jivesoftware.smack.tcp.XMPPTCPConnection﹕ Trying to establish TCP connection to myjabber.com/999.999.999.999 at port 5222
2017-06-21_09-51-09 W/ConnectionThread: username@myjabber.com/Xabber_kavfIM1a: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(Unknown Source)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(Unknown Source)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(Unknown Source)
	at com.xabber.android.data.connection.ConnectionThread.connectAndLogin(Unknown Source)
	at com.xabber.android.data.connection.ConnectionThread$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:818)

2017-06-21_09-51-09 E/ConnectionThread: username@myjabber.com/Xabber_kavfIM1a﹕ org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed
2017-06-21_09-51-09 E/ConnectionThread: username@myjabber.com/Xabber_kavfIM1a﹕ org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(Unknown Source)
2017-06-21_09-51-09 E/ConnectionThread: username@myjabber.com/Xabber_kavfIM1a﹕ org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(Unknown Source)
2017-06-21_09-51-09 E/ConnectionThread: username@myjabber.com/Xabber_kavfIM1a﹕ org.jivesoftware.smack.AbstractXMPPConnection.connect(Unknown Source)
2017-06-21_09-51-09 E/ConnectionThread: username@myjabber.com/Xabber_kavfIM1a﹕ com.xabber.android.data.connection.ConnectionThread.connectAndLogin(Unknown Source)
2017-06-21_09-51-09 E/ConnectionThread: username@myjabber.com/Xabber_kavfIM1a﹕ com.xabber.android.data.connection.ConnectionThread$1.run(Unknown Source)
2017-06-21_09-51-09 E/ConnectionThread: username@myjabber.com/Xabber_kavfIM1a﹕ java.lang.Thread.run(Thread.java:818)
2017-06-21_09-51-09 D/ConnectionThread: username@myjabber.com/Xabber_kavfIM1a﹕ There was no successful connection, disabling account
2017-06-21_09-51-09 D/com.xabber.android.data.notification.NotificationManager@25dd1cd7﹕ Notification: 18, sound: content://settings/system/notification_sound, vibro: 2, light: 4, ticker: ***
2017-06-21_09-51-09 D/AccountItem: username@myjabber.com/Xabber_kavfIM1a﹕ disconnect
2017-06-21_09-51-09 D/AccountItem: username@myjabber.com/Xabber_kavfIM1a﹕ already disconnected
2017-06-21_09-51-09 D/ConnectionThread: username@myjabber.com/Xabber_kavfIM1a﹕ Connection thread finished
```

**Comment by oxoWrk** [comment]
What do you have in "TLS/SSL usage"

**Comment by Dobromyr** [comment]
old SSL

**Comment by ionty** [comment]
Old SLL for me as well.

**Comment by oxoWrk** [comment]
Old SSL uses port 5223. Change port number in Xabber settings or  use TLS

**Comment by Dobromyr** [comment]
> Old SSL uses port 5223. Change port number in Xabber settings or use TLS
Thanks. When I manually change port to 5223 and use SSL connection success

**Comment by ionty** [comment]
For me as well! Thanks a lot!
