### ISSUE TITLE
Error in connecting with server , android 4,5

### ISSUE THREAD

**Issue by sarathraj-coder** [redsolution/xabber-android#744]
> I/MemorizingTrustManager: getAppKeyStore(/data/data/com/app_KeyStore/KeyStore.bks) - exception loading file key store
>                                                            java.io.FileNotFoundException: /data/data/com/app_KeyStore/KeyStore.bks: open failed: ENOENT (No such file or directory)
>                                                                at libcore.io.IoBridge.open(IoBridge.java:420)
>                                                                at java.io.FileInputStream.<init>(FileInputStream.java:78)
>                                                                at de.duenndns.ssl.MemorizingTrustManager.loadAppKeyStore(MemorizingTrustManager.java:330)
>                                                                at de.duenndns.ssl.MemorizingTrustManager.init(MemorizingTrustManager.java:155)
>                                                                at de.duenndns.ssl.MemorizingTrustManager.<init>(MemorizingTrustManager.java:133)
>                                                                at com.xmppapp.android.data.connection.CertificateManager.getNewMemorizingTrustManager(CertificateManager.java:38)
>                                                                at com.xmppapp.android.data.connection.ConnectionBuilder.build(ConnectionBuilder.java:61)
>                                                                at com.xmppapp.android.data.connection.ConnectionItem.createConnection(ConnectionItem.java:100)
>                                                                at com.xmppapp.android.data.connection.ConnectionItem.<init>(ConnectionItem.java:94)
>                                                                at com.xmppapp.android.data.account.AccountItem.<init>(AccountItem.java:122)
>                                                                at com.xmppapp.android.data.account.AccountManager.onLoad(AccountManager.java:207)
>                                                                at com.PlaceOrderApplication.onLoad(PlaceOrderApplication.java:317)
>                                                                at com.PlaceOrderApplication.access$300(PlaceOrderApplication.java:157)
>                                                                at com.PlaceOrderApplication$4.call(PlaceOrderApplication.java:378)
>                                                                at com.PlaceOrderApplication$4.call(PlaceOrderApplication.java:374)
>                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:234)
>                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
>                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
>                                                                at java.lang.Thread.run(Thread.java:841)
>                                                             Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
>                                                                at libcore.io.Posix.open(Native Method)
>                                                                at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
>                                                                at libcore.io.IoBridge.open(IoBridge.java:404)
>                                                                at java.io.FileInputStream.<init>(FileInputStream.java:78) 
>                                                                at de.duenndns.ssl.MemorizingTrustManager.loadAppKeyStore(MemorizingTrustManager.java:330) 
>                                                                at de.duenndns.ssl.MemorizingTrustManager.init(MemorizingTrustManager.java:155) 
>                                                                at de.duenndns.ssl.MemorizingTrustManager.<init>(MemorizingTrustManager.java:133) 
>                                                                at com.xmppapp.android.data.connection.CertificateManager.getNewMemorizingTrustManager(CertificateManager.java:38) 
>                                                                at com.xmppapp.android.data.connection.ConnectionBuilder.build(ConnectionBuilder.java:61) 
>                                                                at com.xmppapp.android.data.connection.ConnectionItem.createConnection(ConnectionItem.java:100) 
>                                                                at com.xmppapp.android.data.connection.ConnectionItem.<init>(ConnectionItem.java:94) 
>                                                                at com.xmppapp.android.data.account.AccountItem.<init>(AccountItem.java:122) 
>                                                                at com.xmppapp.android.data.account.AccountManager.onLoad(AccountManager.java:207) 
>                                                                at com.PlaceOrderApplication.onLoad(PlaceOrderApplication.java:317) 
>                                                                at com.PlaceOrderApplication.access$300(PlaceOrderApplication.java:157) 
>                                                                at com.PlaceOrderApplication$4.call(PlaceOrderApplication.java:378) 
>                                                                at com.PlaceOrderApplication$4.call(PlaceOrderApplication.java:374) 
>                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:234) 
>                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
>                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
>                                                                at java.lang.Thread.run(Thread.java:841)

**Comment by sarathraj-coder** [comment]
its working when i changed the sasl to 

>  private synchronized static void setUpSasl() {
>         // TODO: DIGEST-MD5 mechanism disabled due to implementation problems
>         // should be enabled back when fixed in Smack
>         //SASLAuthentication.blacklistSASLMechanism(SASLDigestMD5Mechanism.NAME);
>         
>         SASLMechanism mechanism = new SASLDigestMD5Mechanism();
>         SASLAuthentication.registerSASLMechanism(mechanism);
>         SASLAuthentication.blacklistSASLMechanism("DIGEST-MD5");
>         SASLAuthentication.unBlacklistSASLMechanism("PLAIN");
>     }
