### ISSUE TITLE
error in release build 

### ISSUE THREAD

**Issue by sarathraj-coder** [redsolution/xabber-android#757]
Getting error in the line : 

               ProviderManager.addLoader(new ProviderFileLoader(getResources().openRawResource(R.raw.smack)));

08-10 14:41:13.083 3313-3374/? E/ProviderFileLoader: Could not find provider class
                                                     java.lang.ClassNotFoundException: Didn't find class "com.sarathraj.apps.placeorderandroid.xmppapp.xmpp.vcardupdate.VCardUpdateProvider" on path: DexPathList[[zip file "/data/app/com.sarathraj.apps.placeorderandroid.planx-2/base.apk"],nativeLibraryDirectories=[/data/app/com.sarathraj.apps.placeorderandroid.planx-2/lib/arm, /data/app/com.sarathraj.apps.placeorderandroid.planx-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                         at org.jivesoftware.smack.provider.ProviderFileLoader.<init>(ProviderFileLoader.java:78)
                                                         at org.jivesoftware.smack.provider.ProviderFileLoader.<init>(ProviderFileLoader.java:50)
                                                         at com.sarathraj.apps.placeorderandroid.PlaceOrderApplication.m(PlaceOrderApplication.java:314)
                                                         at com.sarathraj.apps.placeorderandroid.PlaceOrderApplication.c(PlaceOrderApplication.java:158)
                                                         at com.sarathraj.apps.placeorderandroid.PlaceOrderApplication$8.a(PlaceOrderApplication.java:378)
                                                         at com.sarathraj.apps.placeorderandroid.PlaceOrderApplication$8.call(PlaceOrderApplication.java:374)
                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                         at java.lang.Thread.run(Thread.java:818)
                                                     	Suppressed: java.lang.ClassNotFoundException: com.acelrtech.apps.placeorderandroid.xmppapp.xmpp.vcardupdate.VCardUpdateProvider
                                                         at java.lang.Class.classForName(Native Method)
                                                         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                         		... 11 more
                                                      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
08-10 14:41:13.083 3313-3374/? E/ProviderFileLoader: Could not find provider class
                                                     java.lang.ClassNotFoundException: Didn't find class "com.sarathraj.apps.placeorderandroid.xmppapp.xmpp.ssn.FeatureProvider" on path: DexPathList[[zip file "/data/app/com.sarathraj.apps.placeorderandroid.planx-2/base.apk"],nativeLibraryDirectories=[/data/app/com.sarathraj.apps.placeorderandroid.planx-2/lib/arm, /data/app/com.sarathraj.apps.placeorderandroid.planx-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                         at org.jivesoftware.smack.provider.ProviderFileLoader.<init>(ProviderFileLoader.java:78)
                                                         at org.jivesoftware.smack.provider.ProviderFileLoader.<init>(ProviderFileLoader.java:50)
                                                         at com.sarathraj.apps.placeorderandroid.PlaceOrderApplication.m(PlaceOrderApplication.java:314)
                                                         at com.sarathraj.apps.placeorderandroid.PlaceOrderApplication.c(PlaceOrderApplication.java:158)
                                                         at com.sarathraj.apps.placeorderandroid.PlaceOrderApplication$8.a(PlaceOrderApplication.java:378)
                                                         at com.sarathraj.apps.placeorderandroid.PlaceOrderApplication$8.call(PlaceOrderApplication.java:374)
                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                         at java.lang.Thread.run(Thread.java:818)
                                                     	Suppressed: java.lang.ClassNotFoundException: com.sarathraj.apps.placeorderandroid.xmppapp.xmpp.ssn.FeatureProvider
                                                         at java.lang.Class.classForName(Native Method)
                                                         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                         		... 11 more
                                                      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
08-10 14:41:13.086 3313-3374/? E/ProviderFileLoader: Could not find provider class
                                                     java.lang.ClassNotFoundException: Didn't find class "com.acelrtech.apps.placeorderandroid.xmppapp.xmpp.httpfileupload.SlotProvider" on path: DexPathList[[zip file "/data/app/com.sarathraj.apps.placeorderandroid.planx-2/base.apk"],nativeLibraryDirectories=[/data/app/com.sarathraj.apps.placeorderandroid.planx-2/lib/arm, /data/app/com.sarathraj.apps.placeorderandroid.planx-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                         at org.jivesoftware.smack.provider.ProviderFileLoader.<init>(ProviderFileLoader.java:78)
                                                         at org.jivesoftware.smack.provider.ProviderFileLoader.<init>(ProviderFileLoader.java:50)
                                                         at com.sarathraj.apps.placeorderandroid.PlaceOrderApplication.m(PlaceOrderApplication.java:314)
                                                         at com.sarathraj.apps.placeorderandroid.PlaceOrderApplication.c(PlaceOrderApplication.java:158)
                                                         at com.sarathraj.apps.placeorderandroid.PlaceOrderApplication$8.a(PlaceOrderApplication.java:378)
                                                         at com.sarathraj.apps.placeorderandroid.PlaceOrderApplication$8.call(PlaceOrderApplication.java:374)
                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                         at java.lang.Thread.run(Thread.java:818)
                                                     	Suppressed: java.lang.ClassNotFoundException: com.acelrtech.apps.placeorderandroid.xmppapp.xmpp.httpfileupload.SlotProvider
                                                         at java.lang.Class.classForName(Native Method)
                                                         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                         		... 11 more
                                                      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by Str4tocaster** [comment]
@sarathraj-coder Is there an error in the current version?

**Comment by sarathraj-coder** [comment]
I didn't checked the latest version.
