### ISSUE TITLE
Authorization error. Android build 533, 2.5

### ISSUE THREAD

**Issue by jimcbrodie** [redsolution/xabber-android#850]
Hi, 
For some weeks now, I haven't been able to login to my  Xabber account on my Android device. I can login as normal to the Web version from a PC, so I know there
isn't a problem with my username or password. I have tried uninstalling and reinstalling the app but no joy. 
Any assistance gratefully received! 
I have provided what I hope is the relevant info below. 
Please let me know what more I can try. 
Thank you, 
Jim 

"Authorization error. Please check your login/pass
SASLError using SCRAM-SHA-1: not-authorized" 

Lenovo TB-8704F
Android 7.1.1
Xabber 2.5(533) from Play Store
Host: xabber.org

From the log:
2018-12-01_09-52-12 D/Smack﹕ RECV (1): <failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><not-authorized/><text xml:lang='en'>Invalid username or password</text></failure>
2018-12-01_09-52-12 W/ConnectionThread: jcbrodie@xabber.org/xabber-android-60001hPo: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(Unknown Source)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(Unknown Source)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(Unknown Source)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:761)

**Comment by jimcbrodie** [comment]
Thanks Ilya. Have reset my password, but still getting the same issue.

Best,
Jim

**Comment by oxoWrk** [comment]
What password did you reset: **Xabber Account** password or **XMPP account** password?
Need to reset your **XMPP account** password.  Go to your [Account page](https://www.xabber.com/account/). Click on  **XMPP account**(yourname@xabber.org) in the services section, then "Password and security" -> "Change Password"

**Comment by jimcbrodie** [comment]
Hi Ilya,

That's exactly what I did (twice) - reset my XMPP account password...

Jim

**Comment by andrewnenakhov** [comment]
@jimcbrodie ok I suggest you do the following. Email us info@xabber.com and provide your working xmpp account, we'll contact you. Once there, we'll schedule a time so you'll try to connect our XMPP server and we'll be monitoring connection on serverside. Then we'll know exactly why you can't connect.

**Comment by jimcbrodie** [comment]
Solved: awkward mobile menu layout and mistaken error message.

Thanks!
