### ISSUE TITLE
Possible silence crash in VCardManager

### ISSUE THREAD

**Issue by KonomiKitten** [redsolution/xabber-android#852]
Sometimes Xabber VIP 2.5(533) just closes on it's own, then reopens with no error message it's not an out of memory problem no other apps are doing it and the only errors I can find in my logcat are:

````
12-11 21:22:24.968  8905  8972 W System.err: com.xabber.android.data.extension.vcard.VCardManager@a547b4f
12-11 21:22:24.969  8905  8972 W System.err: org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from removed@removed/removed: XMPPError: service-unavailable - cancel
12-11 21:22:24.969  8905  8972 W System.err: 	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(Unknown Source)
12-11 21:22:24.969  8905  8972 W System.err: 	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(Unknown Source)
12-11 21:22:24.969  8905  8972 W System.err: 	at com.xabber.android.data.extension.vcard.CustomVCardManager.loadVCard(Unknown Source)
12-11 21:22:24.969  8905  8972 W System.err: 	at com.xabber.android.data.extension.vcard.VCardManager.getVCard(Unknown Source)
12-11 21:22:24.969  8905  8972 W System.err: 	at com.xabber.android.data.extension.vcard.VCardManager$3.run(Unknown Source)
12-11 21:22:24.969  8905  8972 W System.err: 	at com.xabber.android.data.Application$9.run(Unknown Source)
12-11 21:22:24.969  8905  8972 W System.err: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
12-11 21:22:24.969  8905  8972 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-11 21:22:24.969  8905  8972 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-11 21:22:24.969  8905  8972 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-11 21:22:24.969  8905  8972 W System.err: 	at java.lang.Thread.run(Thread.java:761)
12-11 21:22:25.994  8905  8972 W System.err: com.xabber.android.data.extension.vcard.VCardManager@a547b4f
12-11 21:22:25.995  8905  8972 W System.err: org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from removed@removed/removed: XMPPError: feature-not-implemented - cancel
12-11 21:22:25.995  8905  8972 W System.err: 	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(Unknown Source)
12-11 21:22:25.995  8905  8972 W System.err: 	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(Unknown Source)
12-11 21:22:25.995  8905  8972 W System.err: 	at com.xabber.android.data.extension.vcard.CustomVCardManager.loadVCard(Unknown Source)
12-11 21:22:25.995  8905  8972 W System.err: 	at com.xabber.android.data.extension.vcard.VCardManager.getVCard(Unknown Source)
12-11 21:22:25.995  8905  8972 W System.err: 	at com.xabber.android.data.extension.vcard.VCardManager$3.run(Unknown Source)
12-11 21:22:25.995  8905  8972 W System.err: 	at com.xabber.android.data.Application$9.run(Unknown Source)
12-11 21:22:25.995  8905  8972 W System.err: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
12-11 21:22:25.995  8905  8972 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-11 21:22:25.995  8905  8972 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-11 21:22:25.995  8905  8972 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-11 21:22:25.995  8905  8972 W System.err: 	at java.lang.Thread.run(Thread.java:761)
````

**Comment by panpansh** [comment]
`feature-not-implemented` is it a smack side ?

**Comment by mehtaketan7** [comment]
any update on this issue? I am facing same issue since long time.
