### ISSUE TITLE
Connection error on Jellybean

### ISSUE THREAD

**Issue by echaskaris** [redsolution/xabber-android#913]
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed
	at com.xabber.xmpp.smack.XMPPTCPConnection.connectUsingConfiguration(Unknown Source)
	at com.xabber.xmpp.smack.XMPPTCPConnection.connectInternal(Unknown Source)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(Unknown Source)
	at com.xabber.android.data.connection.ConnectionThread.connectAndLogin(Unknown Source)
	at com.xabber.android.data.connection.ConnectionThread$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:856)

Phone doesn't have Google Play Services
Works on Kitkat phone with Google Play Services

**Comment by andrewnenakhov** [comment]
You might have encountered a rare bug in connection code, try latest update to Xabber Beta (on Google Play). Please, report here if it helps (or not).

**Comment by echaskaris** [comment]
Doesn't work. Now I get no response exception, while waiting for tls

**Comment by vitaliipopov23** [comment]
There are various problems with connection those can lead to this exception. Cause you doesn't provided another data, we can only advice to check your connection settings: host address, port, proxy, etc or maybe even reinstall app. Or you can provide log-files, steps what you do, and then we try to locate a problem with more accuracy.

**Comment by echaskaris** [comment]
Here 
[Xabber_2.6.6.645_2019-11-28_15-27-16-1517379024.txt](https://github.com/redsolution/xabber-android/files/3902536/Xabber_2.6.6.645_2019-11-28_15-27-16-1517379024.txt)

**Comment by echaskaris** [comment]
Do you see anything in the log?

**Comment by echaskaris** [comment]
@andrewnenakhov @popovvitaly Sorry to ping you but I'd like to get xabber to work

**Comment by vitaliipopov23** [comment]
Android before 5.0 can't enable TLS by default without  using Google Play Services. I think we can't easily fix it, sorry.

**Comment by echaskaris** [comment]
Ok, what about SSL? I can't get that to work either. [Xabber_2.6.6.645_2019-12-16_12-08-29-2124424731.txt](https://github.com/redsolution/xabber-android/files/3969448/Xabber_2.6.6.645_2019-12-16_12-08-29-2124424731.txt)

Also I found this https://stackoverflow.com/questions/37705367/how-do-i-get-tls-1-2-to-work-in-android-4-4-without-the-help-of-google-play-serv

**Comment by bleedingcrow** [comment]
@echaskaris spot on

The newest TLS does _not_ require an android version "upgrade"
