### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by unixcomrade** [redsolution/xabber-android#942]
Hello! I run my own ejabberd server, trying to connect to it with Xabber 2.6.6.645. I do suspect there is something wrong in ejabberd config, and I do understand that this question is rather more appropriate to ejabberd git. After I enabled debug logging:

"2022-10-31 14:37:54.848697+02:00 [error] <0.659.0>@ejabberd_acme:issue_request/7:246 Failed to request certificate for xxxxxxxx.org, pubsub.xxxxxxxx.org and 3 more hosts: Challenge failed for domain conference.xxxxxxxx.org: ACME server reported: DNS problem: NXDOMAIN looking up A for conference.xxxxxxxx.org - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for conference.xxxxxxxxx.org - check that a DNS record exists for this domain (error type: dns)"

Fixed DNS error, added A record for conference.mydomain.org
Still I'm facing with the same error as before. What could be the reason for this? TLS\SSL error?

org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'xxxxxxxx.org:5222' failed because: xxxxxxxx.org/45.x.x.19 exception: java.net.SocketTimeoutException: failed to connect to xxxxxxxxx.org/45.x.x.19 (port 5222) from /192.168.88.252 (port 51551) after 30000ms
 at com.xabber.xmpp.smack.XMPPTCPConnection.connectUsingConfiguration(Unknown Source:334)
 at com.xabber.xmpp.smack.XMPPTCPConnection.connectInternal(Unknown Source:5)
 at org.jivesoftware.smack.AbstractXMPPConnection.connect(Unknown Source:27)
 at com.xabber.android.data.connection.ConnectionThread.connectAndLogin(Unknown Source:207)
 at com.xabber.android.data.connection.ConnectionThread$1.run(Unknown Source:8)
 at java.lang.Thread.run(Thread.java:923)

**Comment by oxoWrk** [comment]
xxxxxxxx.org/45.x.x.19  is exactly the address of host where ejabberd is running?
Check the firewall configuration. Are incoming connections to port  5222 allowed?
